services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: buds
      POSTGRES_USER: buds
      POSTGRES_PASSWORD: buds
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: