services:
  postgres: # сервис для работы с джанго
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: buds
      POSTGRES_USER: buds
      POSTGRES_PASSWORD: buds
    volumes:
      - db:/var/lib/postgresql/data
  
  web: # сервис для джанго
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=buds
      - DB_USER=buds
      - DB_PASSWORD=buds

volumes:
  db: