# Generated by Django 5.2.4 on 2025-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaziCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('birth_datetime', models.DateTimeField(verbose_name='Дата/время рождения')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='CelestialStem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('element', models.CharField(max_length=10, verbose_name='Элемент')),
                ('yin_yang', models.BooleanField(verbose_name='Инь/Ян')),
            ],
        ),
        migrations.CreateModel(
            name='EarthlyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('element', models.CharField(max_length=10, verbose_name='Элемент')),
                ('animal', models.CharField(max_length=20, verbose_name='Животное')),
            ],
        ),
    ]
