# Generated by Django 5.2.4 on 2025-07-10 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bazicalculation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='day_stem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_calc', to='badis.celestialstem'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='hour_stem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_calc', to='badis.celestialstem'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='month_stem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_calc', to='badis.celestialstem'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='year_stem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_calc', to='badis.celestialstem'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='day_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_calc', to='badis.earthlybranch'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='hour_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_calc', to='badis.earthlybranch'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='month_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_calc', to='badis.earthlybranch'),
        ),
        migrations.AddField(
            model_name='bazicalculation',
            name='year_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_calc', to='badis.earthlybranch'),
        ),
    ]
